In [1]:
# Single neuron model implementation using TensorFlow.
# In this example, synaptic weights are passed to 
# network.
#
# Author: Prof. Fabrício Galende Marques de Carvalho
##

from neuron_model_tensorflow import Neuron
import numpy as np

def activation(x):
    return 1. if x>=0 else 0.0


neuron = Neuron([0.6, 0.4], -1.0, activation)

x = np.array([[1.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron.output(x))
print("Pre activation : ", neuron.pre_act)

x = np.array([[0.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron.output(x))
print("Pre activation : ", neuron.pre_act)

2025-06-24 01:20:57.994737: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-24 01:20:58.016782: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-24 01:20:58.634452: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


Neuron output:  1.0
Pre activation :  tf.Tensor([[0.]], shape=(1, 1), dtype=float32)
Neuron output:  0.0
Pre activation :  tf.Tensor([[-0.6]], shape=(1, 1), dtype=float32)


In [2]:
# Now we change to sigmoid (logistic) activation function
neuron = Neuron([0.6, 0.4], -1.0, 'sigmoid')
x = np.array([[1.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron.output(x))
print("Pre activation : ", neuron.pre_act)

x = np.array([[0.0, 1.0]], dtype= np.float32)
print("Neuron output: ", neuron.output(x))
print("Pre activation : ", neuron.pre_act)


Neuron output:  tf.Tensor([[0.5]], shape=(1, 1), dtype=float32)
Pre activation :  tf.Tensor([[0.]], shape=(1, 1), dtype=float32)
Neuron output:  tf.Tensor([[0.35434368]], shape=(1, 1), dtype=float32)
Pre activation :  tf.Tensor([[-0.6]], shape=(1, 1), dtype=float32)
